/*
 * CanPath engine -- JavaScript port of the Python reference implementation.
 *
 * This is a LINE-FOR-LINE port, not a reinterpretation. Any divergence is a
 * bug, and tests/parity.js proves equivalence against fixtures generated by
 * the Python engine. Same discipline applies to the eventual Swift port.
 */

const TAX_2026 = {
  tax_year: 2026,
  federal: {
    brackets: [
      { floor: 0, rate: 0.14 },
      { floor: 58523, rate: 0.205 },
      { floor: 117045, rate: 0.26 },
      { floor: 181440, rate: 0.29 },
      { floor: 258482, rate: 0.33 },
    ],
    credit_rate: 0.14,
    bpa: { base: 14829, additional: 1623, phaseout_start: 181440, phaseout_end: 258482 },
  },
  provinces: {
    BC: {
      name: "British Columbia",
      brackets: [
        { floor: 0, rate: 0.056 },
        { floor: 50363, rate: 0.077 },
        { floor: 100728, rate: 0.105 },
        { floor: 115648, rate: 0.1229 },
        { floor: 140430, rate: 0.147 },
        { floor: 190405, rate: 0.168 },
        { floor: 265545, rate: 0.205 },
      ],
      credit_rate: 0.056, bpa: 13216,
      tax_reduction: { max_credit: 690, threshold: 25570, phaseout_rate: 0.0356 },
    },
    AB: {
      name: "Alberta",
      brackets: [
        { floor: 0, rate: 0.08 },
        { floor: 61200, rate: 0.1 },
        { floor: 154259, rate: 0.12 },
        { floor: 185111, rate: 0.13 },
        { floor: 246813, rate: 0.14 },
        { floor: 370220, rate: 0.15 },
      ],
      credit_rate: 0.08, bpa: 22769,
    },
    SK: {
      name: "Saskatchewan",
      brackets: [
        { floor: 0, rate: 0.105 },
        { floor: 54532, rate: 0.125 },
        { floor: 155805, rate: 0.145 },
      ],
      credit_rate: 0.105, bpa: 20381,
    },
    MB: {
      name: "Manitoba",
      brackets: [
        { floor: 0, rate: 0.108 },
        { floor: 47000, rate: 0.1275 },
        { floor: 100000, rate: 0.174 },
      ],
      credit_rate: 0.108, bpa: 15780,
    },
    ON: {
      name: "Ontario",
      brackets: [
        { floor: 0, rate: 0.0505 },
        { floor: 53891, rate: 0.0915 },
        { floor: 107785, rate: 0.1116 },
        { floor: 150000, rate: 0.1216 },
        { floor: 220000, rate: 0.1316 },
      ],
      credit_rate: 0.0505, bpa: 12989,
    },
    NB: {
      name: "New Brunswick",
      brackets: [
        { floor: 0, rate: 0.094 },
        { floor: 52333, rate: 0.14 },
        { floor: 104666, rate: 0.16 },
        { floor: 193861, rate: 0.195 },
      ],
      credit_rate: 0.094, bpa: 13664,
    },
    NS: {
      name: "Nova Scotia",
      brackets: [
        { floor: 0, rate: 0.0879 },
        { floor: 30995, rate: 0.1495 },
        { floor: 61991, rate: 0.1667 },
        { floor: 97417, rate: 0.175 },
        { floor: 157124, rate: 0.21 },
      ],
      credit_rate: 0.0879, bpa: 11932,
    },
    PE: {
      name: "Prince Edward Island",
      brackets: [
        { floor: 0, rate: 0.095 },
        { floor: 33928, rate: 0.1347 },
        { floor: 65820, rate: 0.166 },
        { floor: 106890, rate: 0.1762 },
        { floor: 142520, rate: 0.19 },
        { floor: 200000, rate: 0.2 },
      ],
      credit_rate: 0.095, bpa: 15000,
      tax_reduction: { max_credit: 350, threshold: 23000, phaseout_rate: 0.05 },
    },
    NL: {
      name: "Newfoundland and Labrador",
      brackets: [
        { floor: 0, rate: 0.087 },
        { floor: 44192, rate: 0.145 },
        { floor: 89354, rate: 0.158 },
        { floor: 159528, rate: 0.178 },
        { floor: 223340, rate: 0.198 },
        { floor: 285319, rate: 0.208 },
        { floor: 570638, rate: 0.213 },
        { floor: 1141275, rate: 0.218 },
      ],
      credit_rate: 0.087, bpa: 15000,
      tax_reduction: { max_credit: 842, threshold: 24191, phaseout_rate: 0.16 },
    },
  },
  benefits: {
    ccb: {
      max_under_6: 8157,
      max_6_to_17: 6883,
      threshold_1: 38237,
      threshold_2: 82847,
      phase1_rates: { 1: 0.07, 2: 0.135, 3: 0.19, 4: 0.23 },
      phase2_rates: { 1: 0.032, 2: 0.057, 3: 0.08, 4: 0.095 },
    },
    bc_family_benefit: {
      max_first_child: 1750, max_second_child: 1100, max_additional_child: 900,
      single_parent_supplement: 500, threshold_1: 30176, threshold_2: 96562,
      phaseout_rate: 0.04,
      floor_first_child: 775, floor_second_child: 750, floor_additional_child: 725,
    },
    provincial_child_benefits: {SK:null,AB:{name:"Alberta Child and Family Benefit",type:"ab",base_amounts:[1529,764],base_threshold:28116,base_rate:.11,working_amounts:[782,712,426,141],working_threshold:47115,working_rate:.15,working_min_employment:2760},MB:{name:"Manitoba Child Benefit",type:"linear",amounts:[420],threshold:15000,rate:.025},ON:{name:"Ontario Child Benefit",type:"linear",amounts:[1759.92],threshold:26865,rate:.08},NB:{name:"New Brunswick Child Tax Benefit",type:"linear",amounts:[250],threshold:20000,rate:.02},NS:{name:"Nova Scotia Child Benefit",type:"linear",amounts:[1524.96],threshold:26000,rate:.5},NL:{name:"Newfoundland and Labrador Child Benefit",type:"linear",amounts:[1887.96,2001.96,2149.92,2310],threshold:20397,rate:.16},PE:{name:"Prince Edward Island Child Benefit",type:"tiered",tiers:[{upto:45000,per_child:409.92},{upto:80000,per_child:289.92}]}},
    cgeb: {
      max_single: 679, max_couple: 890, max_per_child: 234,
      child_age_limit: 19, threshold: 46432, phaseout_rate: 0.05,
    },
  },
  accounts: {
    rrsp: { earned_income_rate: 0.18, dollar_limit: 33810 },
    tfsa: { annual_limit: 7000, cumulative_since_2009: 109000 },
    fhsa: { annual_limit: 8000, lifetime_limit: 40000, max_single_year: 16000 },
    resp: {
      lifetime_contribution: 50000, cesg_match_rate: 0.20, cesg_annual_max: 500,
      cesg_lifetime_max: 7200, cesg_matched_contribution: 2500,
    },
  },
  payroll: {
    cpp: { rate: 0.0595, basic_exemption: 3500, ympe: 74600 },
    cpp2: { rate: 0.04, yampe: 85000 },
    ei: { rate: 0.0163, max_insurable: 68900 },
  },
};

function bracketTax(taxableIncome, brackets) {
  if (taxableIncome <= 0) return 0;
  let tax = 0;
  for (let i = 0; i < brackets.length; i++) {
    const floor = brackets[i].floor;
    if (taxableIncome <= floor) break;
    const ceiling = i + 1 < brackets.length ? brackets[i + 1].floor : Infinity;
    tax += (Math.min(taxableIncome, ceiling) - floor) * brackets[i].rate;
  }
  return tax;
}

function federalBPA(netIncome, cfg) {
  const b = cfg.federal.bpa;
  let additional;
  if (netIncome <= b.phaseout_start) additional = b.additional;
  else if (netIncome >= b.phaseout_end) additional = 0;
  else additional = b.additional * ((b.phaseout_end - netIncome) / (b.phaseout_end - b.phaseout_start));
  return b.base + additional;
}

function federalTax(taxableIncome, cfg) {
  if (taxableIncome <= 0) return 0;
  const gross = bracketTax(taxableIncome, cfg.federal.brackets);
  const credit = federalBPA(taxableIncome, cfg) * cfg.federal.credit_rate;
  return Math.max(0, gross - credit);
}

function provincialTax(taxableIncome, province, cfg) {
  if (taxableIncome <= 0) return 0;
  const p = cfg.provinces[province];
  if (!p) throw new Error(`Province ${province} not supported`);
  let tax = Math.max(0, bracketTax(taxableIncome, p.brackets) - p.bpa * p.credit_rate);
  const tr = p.tax_reduction;
  if (tr) {
    let reduction = tr.max_credit;
    if (taxableIncome > tr.threshold) reduction -= (taxableIncome - tr.threshold) * tr.phaseout_rate;
    tax = Math.max(0, tax - Math.max(0, reduction));
  }
  return tax;
}

const combinedTax = (ti, prov, cfg) => federalTax(ti, cfg) + provincialTax(ti, prov, cfg);

// CPP, CPP2 and EI. Deliberately excluded from the marginal rate -- they are
// levied on gross employment income and an RRSP deduction does not reduce
// them -- but they are most of the gap between gross pay and take-home.
function payrollDeductions(income, cfg) {
  const pr = cfg.payroll;
  const cppBase = Math.max(0, Math.min(income, pr.cpp.ympe) - pr.cpp.basic_exemption);
  const cpp = cppBase * pr.cpp.rate;
  const cpp2 = Math.max(0, Math.min(income, pr.cpp2.yampe) - pr.cpp.ympe) * pr.cpp2.rate;
  const ei = Math.min(income, pr.ei.max_insurable) * pr.ei.rate;
  return { cpp, cpp2, ei, total: cpp + cpp2 + ei };
}

function ccbMax(childAges, cfg) {
  const c = cfg.benefits.ccb;
  return childAges.reduce((t, age) => t + (age < 6 ? c.max_under_6 : age < 18 ? c.max_6_to_17 : 0), 0);
}

function rateFor(n, table) {
  return table[String(Math.min(Math.max(n, 1), 4))];
}

/* Two-zone phase-out. Zone 2 carries the ACCUMULATED zone-1 reduction as a
   fixed amount -- the rates do not stack. */
function canadaChildBenefit(afni, childAges, cfg) {
  const c = cfg.benefits.ccb;
  const n = childAges.filter((a) => a < 18).length;
  if (n === 0) return 0;
  const maximum = ccbMax(childAges, cfg);
  const { threshold_1: t1, threshold_2: t2 } = c;
  let reduction;
  if (afni <= t1) reduction = 0;
  else if (afni <= t2) reduction = rateFor(n, c.phase1_rates) * (afni - t1);
  else reduction = rateFor(n, c.phase1_rates) * (t2 - t1) + rateFor(n, c.phase2_rates) * (afni - t2);
  return Math.max(0, maximum - reduction);
}


/* BC Family Benefit: two 4% clawback bands with a FLAT PLATEAU between.
   The benefit reduces at 4% above threshold_1 but never below a per-child
   floor; the floor holds (costing nothing at the margin) until threshold_2,
   then reduces at 4% again. Modelling it as one continuous phase-out puts
   the clawback in the wrong income bands entirely. */
function bcFamilyBenefit(afni,ages,cfg,singleParent){const b=cfg.benefits.bc_family_benefit;
  if(!b)return 0;const n=ages.filter(a=>a<18).length;if(!n)return 0;
  let mx=b.max_first_child,fl=b.floor_first_child;
  if(n>=2){mx+=b.max_second_child;fl+=b.floor_second_child;}
  if(n>2){mx+=b.max_additional_child*(n-2);fl+=b.floor_additional_child*(n-2);}
  if(singleParent)mx+=b.single_parent_supplement;
  const r=b.phaseout_rate,t1=b.threshold_1,t2=b.threshold_2;
  let v=Math.max(fl,mx-r*Math.max(0,Math.min(afni,t2)-t1));
  if(afni>t2)v-=r*(afni-t2);
  return Math.max(0,v);}
/* CGEB (the renamed GST/HST credit). Age limit is under 19, NOT the CCB's 18. */
function cgeb(afni,h,cfg){const c=cfg.benefits.cgeb;if(!c)return 0;
  const kids=(h.child_ages||[]).filter(a=>a<c.child_age_limit).length;
  const partnered=h.partnered!=null?h.partnered:(h.partner_income||0)>0;
  const mx=(partnered?c.max_couple:c.max_single)+c.max_per_child*kids;
  return Math.max(0,mx-c.phaseout_rate*Math.max(0,afni-c.threshold));}

/* Provincial child benefits other than BC's. linear = one rate; tiered = a
   literal STEP, i.e. a real cliff, not a phase-out; ab = Alberta's two
   independent components. A province mapped to null has none at all. */
const stackedMax=(amts,n)=>{let t=0;for(let i=0;i<n;i++)t+=amts[Math.min(i,amts.length-1)];return t;};
function provincialChildBenefit(afni,ages,prov,cfg,employmentIncome){
  const tbl=cfg.benefits.provincial_child_benefits||{},b=tbl[prov];
  if(!b)return 0;
  const n=ages.filter(a=>a<18).length;if(!n)return 0;
  if(b.type==="linear")
    return Math.max(0,stackedMax(b.amounts,n)-b.rate*Math.max(0,afni-b.threshold));
  if(b.type==="tiered"){
    for(const t of b.tiers)if(afni<=t.upto)return t.per_child*n;
    return 0;}
  if(b.type==="ab"){
    const base=Math.max(0,stackedMax(b.base_amounts,n)
      -b.base_rate*Math.max(0,afni-b.base_threshold));
    const earned=employmentIncome==null?afni:employmentIncome;
    let work=0;
    if(earned>b.working_min_employment)
      work=Math.max(0,stackedMax(b.working_amounts,n)
        -b.working_rate*Math.max(0,afni-b.working_threshold));
    return base+work;}
  return 0;}
function totalBenefits(afni,h,cfg){
  const partnered=h.partnered!=null?h.partnered:(h.partner_income||0)>0;
  const ccb=canadaChildBenefit(afni,h.child_ages,cfg);
  const bcfb=h.province==="BC"?bcFamilyBenefit(afni,h.child_ages,cfg,!partnered):0;
  const pcb=provincialChildBenefit(afni,h.child_ages,h.province,cfg);
  const g=cgeb(afni,h,cfg);
  return{ccb,bcfb,pcb,cgeb:g,total:ccb+bcfb+pcb+g};}

function netPosition(income, household, cfg, deduction = 0) {
  const taxable = Math.max(0, income - deduction);
  const partner = Math.max(0, household.partner_income || 0);
  const afni = taxable + partner; // BOTH partners' net incomes
  const tax = combinedTax(taxable, household.province, cfg);
  const partnerTax = partner ? combinedTax(partner, household.province, cfg) : 0;
  const benefits = totalBenefits(afni, household, cfg).total;
  return {
    gross_income: income, partner_income: partner, deduction,
    taxable_income: taxable, afni, tax, partner_tax: partnerTax,
    household_tax: tax + partnerTax, benefits,
    net_cash: income + partner - deduction - tax - partnerTax + benefits,
  };
}

function effectiveMarginalRate(income, household, cfg, delta = 100) {
  const lo = netPosition(income, household, cfg);
  const hi = netPosition(income + delta, household, cfg);
  const statutory = (hi.tax - lo.tax) / delta;
  const clawback = (lo.benefits - hi.benefits) / delta;
  return { income, statutory_rate: statutory, clawback_rate: clawback, effective_rate: statutory + clawback };
}

function valueOfContribution(income, contribution, household, cfg) {
  const before = netPosition(income, household, cfg, 0);
  const after = netPosition(income, household, cfg, contribution);
  const refund = before.tax - after.tax;
  const benefit = after.benefits - before.benefits;
  const total = refund + benefit;
  return {
    contribution, tax_refund: refund, benefit_restored: benefit, total_value: total,
    blended_rate: contribution ? total / contribution : 0,
    refund_share: total ? refund / total : 0,
  };
}

function optimize(profile, cfg, chunk = 250) {
  const a = cfg.accounts;
  const rrspRoom = profile.rrsp_room ?? Math.min(profile.income * a.rrsp.earned_income_rate, a.rrsp.dollar_limit);
  const tfsaRoom = profile.tfsa_room ?? a.tfsa.annual_limit;
  // FHSA is capped over a lifetime ($40,000), not only per year. Handing out
  // the annual limit indefinitely models an account that runs forever.
  const fhsaLife = profile.fhsa_lifetime_remaining ?? a.fhsa.lifetime_limit;
  const fhsaRoom = profile.fhsa_room ??
    (profile.fhsa_eligible ? Math.min(a.fhsa.annual_limit, Math.max(0, fhsaLife)) : 0);

  const allocated = { employer_match: 0, fhsa: 0, resp: 0, rrsp: 0, tfsa: 0, non_registered: 0 };
  // RESP room means "contribution that still attracts the 20% grant".
  const respKids = profile.resp_children ??
    ((profile.household && profile.household.child_ages) || []).filter((x) => x < 18).length;
  const cesgLeft = profile.cesg_remaining ?? a.resp.cesg_lifetime_max * respKids;
  const respRoom = Math.max(0, Math.min(a.resp.cesg_matched_contribution * respKids,
    a.resp.cesg_match_rate ? cesgLeft / a.resp.cesg_match_rate : 0));
  const room = { fhsa: fhsaRoom, tfsa: tfsaRoom, resp: respRoom };
  // Employer match and RRSP share ONE pool: a group-RRSP match consumes the
  // same room the employee's own contributions do, and each matched dollar
  // costs (1 + rate) of it.
  let pool = rrspRoom;
  let matchLeft = profile.employer_match_cap || 0;
  const mult = 1 + (profile.employer_match_rate || 0);
  const steps = [];
  // Order accounts were FIRST funded in; the allocation object is unordered.
  const sequence = [];
  let remaining = profile.savings_capacity;
  let deducted = 0;
  let guard = 0;

  while (remaining > 0.01 && guard++ < 10000) {
    let amount = Math.min(chunk, remaining);
    const emr = effectiveMarginalRate(profile.income - deducted, profile.household, cfg).effective_rate;
    const matchRoom = Math.min(matchLeft, pool / mult);

    const scores = {};
    if (matchRoom > 0) scores.employer_match = (profile.employer_match_rate || 0) + emr;
    if (room.fhsa > 0) scores.fhsa = emr;
    // Grant rate alone: an RESP contribution is not deductible.
    if (room.resp > 0) scores.resp = a.resp.cesg_match_rate;
    if (pool > 0) scores.rrsp = emr - profile.expected_retirement_rate;
    if (room.tfsa > 0) scores.tfsa = 0;

    const keys = Object.keys(scores);
    let best;
    // Registered room beats a taxable account even at a negative score: this
    // scores YEAR ONE, and a taxable account's cost is the tax on every year
    // of growth after it. 19.6% in / 25% out scores -5.4 but still returns
    // 7.10 per after-tax dollar over 30y at 7% against 6.79 taxable.
    if (keys.length === 0 || Math.max(...keys.map((k) => scores[k])) < 0) {
      if (room.tfsa > 0) best = "tfsa";
      else if (pool > 0) best = "rrsp";
      else { allocated.non_registered += amount; remaining -= amount; continue; }
    } else {
      best = keys.reduce((x, y) => (scores[y] > scores[x] ? y : x));
    }

    if (best === "employer_match") amount = Math.min(amount, matchRoom);
    else if (best === "rrsp") amount = Math.min(amount, pool);
    else amount = Math.min(amount, room[best]);
    if (amount <= 1e-9) { allocated.non_registered += remaining; remaining = 0; continue; }

    if (best === "employer_match") { matchLeft -= amount; pool -= amount * mult; }
    else if (best === "rrsp") pool -= amount;
    else room[best] -= amount;

    allocated[best] += amount;
    remaining -= amount;
    if (sequence.indexOf(best) < 0) sequence.push(best);
    // "resp" is deliberately absent -- contributions are not deductible.
    if (best === "rrsp" || best === "fhsa" || best === "employer_match") deducted += amount;
    steps.push({ account: best, amount, emr_at_step: emr });
  }

  const before = netPosition(profile.income, profile.household, cfg, 0);
  const after = netPosition(profile.income, profile.household, cfg, deducted);
  const allocation = {};
  for (const [k, v] of Object.entries(allocated)) if (v > 0) allocation[k] = v;

  return {
    allocation, sequence, total_deducted: deducted,
    rrsp_room_used: rrspRoom - pool, rrsp_room_left: pool,
    tax_refund: before.tax - after.tax,
    benefit_restored: after.benefits - before.benefits,
    employer_match_earned: allocated.employer_match * (profile.employer_match_rate || 0),
    resp_grant_earned: allocated.resp * a.resp.cesg_match_rate,
    warnings: guardrails(profile, cfg, allocated, pool), steps,
  };
}

function guardrails(profile, cfg, allocated, rrspLeft) {
  const w = [];
  const emr = effectiveMarginalRate(profile.income, profile.household, cfg).effective_rate;
  if (emr < profile.expected_retirement_rate)
    w.push(`RRSP contributions look value-destroying here: your effective rate now (${(emr * 100).toFixed(1)}%) is below the rate you expect to withdraw at (${(profile.expected_retirement_rate * 100).toFixed(1)}%). Fill the TFSA first.`);
  if (profile.income < 45000)
    w.push("At this income, RRSP or RRIF withdrawals in retirement may trigger GIS clawback of roughly 50 cents on the dollar. TFSA withdrawals do not affect GIS.");
  if (profile.fhsa_eligible && (profile.fhsa_room ?? cfg.accounts.fhsa.annual_limit) > 0)
    w.push("FHSA room is unused. It is the only account that is both deductible going in and tax-free coming out.");
  // An employer match larger than the room available to absorb it is not
  // free money; the CRA penalises the over-contribution at 1% a month.
  // Only when room is what ran out -- someone saving less than their
  // employer would match has a different problem.
  if (allocated && (profile.employer_match_cap || 0) > 0 &&
      rrspLeft != null && rrspLeft <= 0.01 &&
      allocated.employer_match < profile.employer_match_cap - 0.01)
    w.push(`Your RRSP room only covers $${Math.round(allocated.employer_match).toLocaleString("en-CA")} of the $${Math.round(profile.employer_match_cap).toLocaleString("en-CA")} your employer will match. The match uses the same room your own contributions do. Check your room in CRA My Account before topping up.`);
  return w;
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = { TAX_2026, bracketTax, federalBPA, federalTax, provincialTax, combinedTax,
    canadaChildBenefit, bcFamilyBenefit, provincialChildBenefit, cgeb, totalBenefits,
    netPosition, effectiveMarginalRate, valueOfContribution, optimize,
    payrollDeductions };
}
