/*
 * CanPath engine -- JavaScript port of the Python reference implementation.
 *
 * This is a LINE-FOR-LINE port, not a reinterpretation. Any divergence is a
 * bug, and tests/parity.js proves equivalence against fixtures generated by
 * the Python engine. Same discipline applies to the eventual Swift port.
 */

const TAX_2026 = {
  tax_year: 2026,
  federal: {
    brackets: [
      { floor: 0, rate: 0.14 },
      { floor: 58523, rate: 0.205 },
      { floor: 117045, rate: 0.26 },
      { floor: 181440, rate: 0.29 },
      { floor: 258482, rate: 0.33 },
    ],
    credit_rate: 0.14,
    bpa: { base: 14829, additional: 1623, phaseout_start: 181440, phaseout_end: 258482 },
  },
  provinces: {
    BC: {
      name: "British Columbia",
      brackets: [
        { floor: 0, rate: 0.056 },
        { floor: 50363, rate: 0.077 },
        { floor: 100728, rate: 0.105 },
        { floor: 115648, rate: 0.1229 },
        { floor: 140430, rate: 0.147 },
        { floor: 190405, rate: 0.168 },
        { floor: 265545, rate: 0.205 },
      ],
      credit_rate: 0.056,
      bpa: 13216,
      tax_reduction: { max_credit: 690, threshold: 25570, phaseout_rate: 0.0356 },
    },
  },
  benefits: {
    ccb: {
      max_under_6: 8157,
      max_6_to_17: 6883,
      threshold_1: 38237,
      threshold_2: 82847,
      phase1_rates: { 1: 0.07, 2: 0.135, 3: 0.19, 4: 0.23 },
      phase2_rates: { 1: 0.032, 2: 0.057, 3: 0.08, 4: 0.095 },
    },
  },
  accounts: {
    rrsp: { earned_income_rate: 0.18, dollar_limit: 33810 },
    tfsa: { annual_limit: 7000, cumulative_since_2009: 109000 },
    fhsa: { annual_limit: 8000, lifetime_limit: 40000, max_single_year: 16000 },
  },
};

function bracketTax(taxableIncome, brackets) {
  if (taxableIncome <= 0) return 0;
  let tax = 0;
  for (let i = 0; i < brackets.length; i++) {
    const floor = brackets[i].floor;
    if (taxableIncome <= floor) break;
    const ceiling = i + 1 < brackets.length ? brackets[i + 1].floor : Infinity;
    tax += (Math.min(taxableIncome, ceiling) - floor) * brackets[i].rate;
  }
  return tax;
}

function federalBPA(netIncome, cfg) {
  const b = cfg.federal.bpa;
  let additional;
  if (netIncome <= b.phaseout_start) additional = b.additional;
  else if (netIncome >= b.phaseout_end) additional = 0;
  else additional = b.additional * ((b.phaseout_end - netIncome) / (b.phaseout_end - b.phaseout_start));
  return b.base + additional;
}

function federalTax(taxableIncome, cfg) {
  if (taxableIncome <= 0) return 0;
  const gross = bracketTax(taxableIncome, cfg.federal.brackets);
  const credit = federalBPA(taxableIncome, cfg) * cfg.federal.credit_rate;
  return Math.max(0, gross - credit);
}

function provincialTax(taxableIncome, province, cfg) {
  if (taxableIncome <= 0) return 0;
  const p = cfg.provinces[province];
  if (!p) throw new Error(`Province ${province} not supported`);
  let tax = Math.max(0, bracketTax(taxableIncome, p.brackets) - p.bpa * p.credit_rate);
  const tr = p.tax_reduction;
  if (tr) {
    let reduction = tr.max_credit;
    if (taxableIncome > tr.threshold) reduction -= (taxableIncome - tr.threshold) * tr.phaseout_rate;
    tax = Math.max(0, tax - Math.max(0, reduction));
  }
  return tax;
}

const combinedTax = (ti, prov, cfg) => federalTax(ti, cfg) + provincialTax(ti, prov, cfg);

function ccbMax(childAges, cfg) {
  const c = cfg.benefits.ccb;
  return childAges.reduce((t, age) => t + (age < 6 ? c.max_under_6 : age < 18 ? c.max_6_to_17 : 0), 0);
}

function rateFor(n, table) {
  return table[String(Math.min(Math.max(n, 1), 4))];
}

/* Two-zone phase-out. Zone 2 carries the ACCUMULATED zone-1 reduction as a
   fixed amount -- the rates do not stack. */
function canadaChildBenefit(afni, childAges, cfg) {
  const c = cfg.benefits.ccb;
  const n = childAges.filter((a) => a < 18).length;
  if (n === 0) return 0;
  const maximum = ccbMax(childAges, cfg);
  const { threshold_1: t1, threshold_2: t2 } = c;
  let reduction;
  if (afni <= t1) reduction = 0;
  else if (afni <= t2) reduction = rateFor(n, c.phase1_rates) * (afni - t1);
  else reduction = rateFor(n, c.phase1_rates) * (t2 - t1) + rateFor(n, c.phase2_rates) * (afni - t2);
  return Math.max(0, maximum - reduction);
}

function netPosition(income, household, cfg, deduction = 0) {
  const taxable = Math.max(0, income - deduction);
  const partner = Math.max(0, household.partner_income || 0);
  const afni = taxable + partner; // BOTH partners' net incomes
  const tax = combinedTax(taxable, household.province, cfg);
  const partnerTax = partner ? combinedTax(partner, household.province, cfg) : 0;
  const benefits = canadaChildBenefit(afni, household.child_ages, cfg);
  return {
    gross_income: income, partner_income: partner, deduction,
    taxable_income: taxable, afni, tax, partner_tax: partnerTax,
    household_tax: tax + partnerTax, benefits,
    net_cash: income + partner - deduction - tax - partnerTax + benefits,
  };
}

function effectiveMarginalRate(income, household, cfg, delta = 100) {
  const lo = netPosition(income, household, cfg);
  const hi = netPosition(income + delta, household, cfg);
  const statutory = (hi.tax - lo.tax) / delta;
  const clawback = (lo.benefits - hi.benefits) / delta;
  return { income, statutory_rate: statutory, clawback_rate: clawback, effective_rate: statutory + clawback };
}

function valueOfContribution(income, contribution, household, cfg) {
  const before = netPosition(income, household, cfg, 0);
  const after = netPosition(income, household, cfg, contribution);
  const refund = before.tax - after.tax;
  const benefit = after.benefits - before.benefits;
  const total = refund + benefit;
  return {
    contribution, tax_refund: refund, benefit_restored: benefit, total_value: total,
    blended_rate: contribution ? total / contribution : 0,
    refund_share: total ? refund / total : 0,
  };
}

function optimize(profile, cfg, chunk = 250) {
  const a = cfg.accounts;
  const rrspRoom = profile.rrsp_room ?? Math.min(profile.income * a.rrsp.earned_income_rate, a.rrsp.dollar_limit);
  const tfsaRoom = profile.tfsa_room ?? a.tfsa.annual_limit;
  const fhsaRoom = profile.fhsa_room ?? (profile.fhsa_eligible ? a.fhsa.annual_limit : 0);

  const allocated = { employer_match: 0, fhsa: 0, rrsp: 0, tfsa: 0, non_registered: 0 };
  const room = { employer_match: profile.employer_match_cap || 0, fhsa: fhsaRoom, rrsp: rrspRoom, tfsa: tfsaRoom };
  const steps = [];
  let remaining = profile.savings_capacity;
  let deducted = 0;
  let guard = 0;

  while (remaining > 0.01 && guard++ < 10000) {
    let amount = Math.min(chunk, remaining);
    const emr = effectiveMarginalRate(profile.income - deducted, profile.household, cfg).effective_rate;

    const scores = {};
    if (room.employer_match > 0) scores.employer_match = (profile.employer_match_rate || 0) + emr;
    if (room.fhsa > 0) scores.fhsa = emr;
    if (room.rrsp > 0) scores.rrsp = emr - profile.expected_retirement_rate;
    if (room.tfsa > 0) scores.tfsa = 0;

    const keys = Object.keys(scores);
    let best;
    if (keys.length === 0 || Math.max(...keys.map((k) => scores[k])) < 0) {
      if (room.tfsa > 0) best = "tfsa";
      else { allocated.non_registered += amount; remaining -= amount; continue; }
    } else {
      best = keys.reduce((x, y) => (scores[y] > scores[x] ? y : x));
    }

    amount = Math.min(amount, room[best]);
    allocated[best] += amount;
    room[best] -= amount;
    remaining -= amount;
    if (best === "rrsp" || best === "fhsa" || best === "employer_match") deducted += amount;
    steps.push({ account: best, amount, emr_at_step: emr });
  }

  const before = netPosition(profile.income, profile.household, cfg, 0);
  const after = netPosition(profile.income, profile.household, cfg, deducted);
  const allocation = {};
  for (const [k, v] of Object.entries(allocated)) if (v > 0) allocation[k] = v;

  return {
    allocation, total_deducted: deducted,
    tax_refund: before.tax - after.tax,
    benefit_restored: after.benefits - before.benefits,
    employer_match_earned: allocated.employer_match * (profile.employer_match_rate || 0),
    warnings: guardrails(profile, cfg), steps,
  };
}

function guardrails(profile, cfg) {
  const w = [];
  const emr = effectiveMarginalRate(profile.income, profile.household, cfg).effective_rate;
  if (emr < profile.expected_retirement_rate)
    w.push(`RRSP contributions look value-destroying here: your effective rate now (${(emr * 100).toFixed(1)}%) is below the rate you expect to withdraw at (${(profile.expected_retirement_rate * 100).toFixed(1)}%). Fill the TFSA first.`);
  if (profile.income < 45000)
    w.push("At this income, RRSP or RRIF withdrawals in retirement may trigger GIS clawback of roughly 50 cents on the dollar. TFSA withdrawals do not affect GIS.");
  if (profile.fhsa_eligible && (profile.fhsa_room ?? cfg.accounts.fhsa.annual_limit) > 0)
    w.push("FHSA room is unused. It is the only account that is both deductible going in and tax-free coming out.");
  return w;
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = { TAX_2026, bracketTax, federalBPA, federalTax, provincialTax, combinedTax,
    canadaChildBenefit, netPosition, effectiveMarginalRate, valueOfContribution, optimize };
}
